WebsiteRanking/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace WebsiteRanking.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

WebsiteRanking/Models/WebRanking.cs
namespace WebsiteRanking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("WebRanking")]
    public partial class WebRanking
    {
        public int Id { get; set; }

        public DateTime? Date { get; set; }

        [StringLength(200)]
        public string Website { get; set; }

        public int? Visits { get; set; }
    }
}

WebsiteRanking/Models/WebRankingModel.cs
namespace WebsiteRanking.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class WebRankingModel : DbContext
    {
        public WebRankingModel()
            : base("name=WebRankingModel")
        {
        }

        public virtual DbSet<WebRanking> WebRankings { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

WebsiteRanking/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using WebsiteRanking.Areas.HelpPage.Models;

namespace WebsiteRanking.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

WebsiteRanking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteRanking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

WebsiteRanking/Controllers/WebRankingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

using System.Data.Entity; 
using WebsiteRanking.Models;
using System.Data.Entity.Infrastructure; 

namespace WebsiteRanking.Controllers
{
    public class WebRankingController : ApiController
    {
        private WebRankingModel db = new WebRankingModel();

        [HttpGet]
        public IEnumerable<WebRanking> Get()
        {
            return db.WebRankings.AsEnumerable();
        }

        [HttpGet]
        public IEnumerable<WebRanking> GetTopFiveByDate(string selectedDate)
        {
            var convertDate = Convert.ToDateTime(selectedDate);
            var web = db.WebRankings.Where(x => x.Date == convertDate).OrderByDescending(x => x.Visits).Take(5).AsEnumerable();
            if (web == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return web;
        }

        [HttpGet]
        public IEnumerable<WebRanking> GetTopFiveByMonth(int month, int year)
        {
            var web = db.WebRankings.Where(x => x.Date.Value.Month == month && x.Date.Value.Year == year).OrderByDescending(x => x.Visits).Take(5).AsEnumerable();
            if (web == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return web;
        }

        [HttpGet]
        public IEnumerable<WebRanking> GetTopFiveByYear(int year)
        {
            var web = db.WebRankings.Where(x => x.Date.Value.Year == year).OrderByDescending(x => x.Visits).Take(5).AsEnumerable();
            if (web == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return web;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        } 
    }
}

WebsiteRanking/Views/Home/Index.cshtml
<h2>Top 5 Websites Ranking</h2>

<div ng-app="app" ng-controller="webRankController" class="container">
    <strong class="error">{{ error }}</strong>

    <div class="row">
        <div class="logs-table col-xs-12">
            <form name="myForm">
                <label>Select Date: </label>
                <input type="date" ng-model="selectedDate" />
                <button ng-click="getTopFiveByDate()">Top 5 by Date</button>
                <button ng-click="getTopFiveByMonth()">Top 5 by Month</button>
                <button ng-click="getTopFiveByYear()">Top 5 by Year</button>
                <br />

                <table class="table table-bordered table-hover" style="width:100%">
                    <tr>
                        <th>Date</th>
                        <th>Website</th>
                        <th>Visits</th>
                    </tr>

                    <tr ng-repeat="webRank in WebRankings">
                        <td>{{ webRank.Date | date: 'yyyy-MM-dd' }}</td>
                        <td>{{ webRank.Website }}</td>
                        <td>{{ webRank.Visits }}</td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
</div>

WebsiteRanking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angularjs")  
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>